---
title: "p8105_hw2_csc2233"
author: "Cameron Chesbrough"
date: "2024-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

# Problem 2

```{r}
trash_df = read_excel("202409 Trash Wheel Collection Data.xlsx",
                      sheet = 1, cell_cols("A:N"))

trash_df = janitor::clean_names(trash_df) %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = round(sports_balls)) %>%
  mutate(sports_balls = as.integer(sports_balls)) %>%
  mutate(year = as.integer(year))

name = rep("Mr_Trash_Wheel", nrow(trash_df))
Mr_trash_df = cbind(name, trash_df)

###

trash_df2 = read_excel("202409 Trash Wheel Collection Data.xlsx",
                      sheet = 2)

trash_df2 = janitor::clean_names(trash_df2) %>%
    drop_na(dumpster) %>%
    mutate(year = as.integer(year))

name = rep("Professor_Trash_Wheel", nrow(trash_df2))
Professor_trash_df = cbind(name, trash_df2)

###

trash_df3 = read_excel("202409 Trash Wheel Collection Data.xlsx",
                      sheet = 4)

trash_df3 = janitor::clean_names(trash_df3) %>%
    drop_na(dumpster)

name = rep("Gwynnda", nrow(trash_df3))
Gwynnda_df = cbind(name, trash_df3)

###

all_trash_df = full_join(Mr_trash_df, Professor_trash_df)
final_trash_df = full_join(all_trash_df, Gwynnda_df)

```

# Writeup for 2



# Problem 3

```{r}

bakers_df = read_csv(file = "./gbb_datasets/bakers.csv")
bakes_df = read_csv(file = "./gbb_datasets/bakes.csv")
results_df = read_csv(file = "./gbb_datasets/results.csv", skip = 2)

bakers_df = janitor::clean_names(bakers_df)
bakes_df = janitor::clean_names(bakes_df)
results_df = janitor::clean_names(results_df) %>%
  drop_na(result)

firsts = separate(bakers_df, col = baker_name, c("first_Name","last_Name"))
bakes_df$baker = str_replace_all(bakes_df$baker, '"', "")
results_df$baker = str_replace_all(results_df$baker, 'Joanne', "Jo")

testing = full_join(results_df, bakes_df, by = c("episode" = "episode",
                                                  "series" = "series",
                                                  "baker" = "baker"))

final_merge = right_join(testing, firsts, by = c("baker" = "first_Name",
                                                 "series" = "series"))

final_merge = arrange(final_merge, series, baker, episode)

write.csv(final_merge, "./gbb_datasets/merged_gbb_data.csv")

```

# Explaining Process

```{r}

later_winners = filter(final_merge, result %in% c("WINNER", "STAR BAKER")) %>%
  filter(series > 4) %>%
  knitr::kable()

later_winners

viewers_df = read_csv(file = "./gbb_datasets/viewers.csv")
viewers_df = janitor::clean_names(viewers_df)
viewers_df

```

# Viewership


